# Generated by Django 6.0.4 on 2026-04-10 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'chat_mode', 'status'], name='ix_session_user_mode_status'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'awaiting_response'])), fields=('user', 'chat_mode'), name='uq_one_open_session_per_user_mode'),
        ),
    ]
