# Generated by Django 6.0.4 on 2026-04-10 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_integration_job'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.userintegration')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_jobs', to='core.message')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='ix_job_status_scheduled_at')],
            },
        ),
    ]
